apiVersion: apps/v1
kind: Deployment
metadata:
  name: fronted
spec:
  selector:
    matchLabels:
      app: fronted
  template:
    metadata:
      labels:
        app: fronted
    spec:
      containers:
      - name: fronted
        image: gcr.io/my-project-600-339318/frontend:null.8
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
